// This file is generated by kconfig_compiler from ktorrent.kcfg.
// All changes you do to this file will be lost.

#include "settings.h"

#include <kstaticdeleter.h>

Settings *Settings::mSelf = 0;
static KStaticDeleter<Settings> staticSettingsDeleter;

Settings *Settings::self()
{
  if ( !mSelf ) {
    staticSettingsDeleter.setObject( mSelf, new Settings() );
    mSelf->readConfig();
  }

  return mSelf;
}

Settings::Settings(  )
  : KConfigSkeleton( QString::fromLatin1( "ktorrentrc" ) )
{
  mSelf = this;
  setCurrentGroup( QString::fromLatin1( "downloads" ) );

  KConfigSkeleton::ItemInt  *itemmaxDownloads;
  itemmaxDownloads = new KConfigSkeleton::ItemInt( currentGroup(), QString::fromLatin1( "maxDownloads" ), mMaxDownloads, 2 );
  itemmaxDownloads->setMinValue(0);
  addItem( itemmaxDownloads, QString::fromLatin1( "maxDownloads" ) );
  KConfigSkeleton::ItemInt  *itemmaxConnections;
  itemmaxConnections = new KConfigSkeleton::ItemInt( currentGroup(), QString::fromLatin1( "maxConnections" ), mMaxConnections, 100 );
  itemmaxConnections->setMinValue(0);
  addItem( itemmaxConnections, QString::fromLatin1( "maxConnections" ) );
  KConfigSkeleton::ItemInt  *itemmaxUploadRate;
  itemmaxUploadRate = new KConfigSkeleton::ItemInt( currentGroup(), QString::fromLatin1( "maxUploadRate" ), mMaxUploadRate, 5 );
  itemmaxUploadRate->setMinValue(0);
  addItem( itemmaxUploadRate, QString::fromLatin1( "maxUploadRate" ) );
  KConfigSkeleton::ItemInt  *itemport;
  itemport = new KConfigSkeleton::ItemInt( currentGroup(), QString::fromLatin1( "port" ), mPort, 6881 );
  itemport->setMinValue(0);
  itemport->setMaxValue(65535);
  addItem( itemport, QString::fromLatin1( "port" ) );
  KConfigSkeleton::ItemBool  *itemshowSystemTrayIcon;
  itemshowSystemTrayIcon = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "showSystemTrayIcon" ), mShowSystemTrayIcon, true );
  addItem( itemshowSystemTrayIcon, QString::fromLatin1( "showSystemTrayIcon" ) );
  KConfigSkeleton::ItemBool  *itemkeepSeeding;
  itemkeepSeeding = new KConfigSkeleton::ItemBool( currentGroup(), QString::fromLatin1( "keepSeeding" ), mKeepSeeding, true );
  addItem( itemkeepSeeding, QString::fromLatin1( "keepSeeding" ) );
}

Settings::~Settings()
{
  if ( mSelf == this )
    staticSettingsDeleter.setObject( mSelf, 0, false );
}

